joshsoftware/providesk_admin_ui

src/apis/apiConfigInitializer.ts
src/apis/apiHelper.ts
src/apis/types.ts
src/services/login.services.ts

- request interceptor for setting auth token
- response interceptor to handle the redirect to login on session expired error

Axios Interceptor Setup

---

src/layouts/sidebar/DropDown.tsx
src/layouts/sidebar/sidebarConfig.tsx
src/modules/Category/components/CategoryList.tsx
src/modules/Category/index.tsx
src/modules/Department/index.tsx
src/modules/Ticket/index.tsx
src/modules/Users/components/EditUser.tsx
src/modules/Users/index.tsx
src/modules/dashboard/dashboard.scss
src/modules/dashboard/index.tsx
src/modules/shared/Select.tsx
src/stylesheets/_global.scss

List Page UI/Layout Fixes

---

src/modules/Reports/components/Overduetime.tsx
src/modules/Reports/components/Ticket.tsx
src/modules/dashboard/CardsView.tsx
src/modules/dashboard/index.tsx
src/modules/details/components/Timeline.tsx
src/modules/details/constants.ts
src/modules/details/index.tsx
src/modules/shared/ComplaintCard.tsx
src/modules/shared/TableComponet.tsx
src/theme.js

Overdue Page and Ticket Component UI

Analysis Report UI

---

src/modules/Auth/auth.scss
src/modules/Auth/index.tsx
src/modules/dashboard/BulkUpdateComponet.tsx
src/modules/dashboard/index.tsx
src/stylesheets/_variables.scss

Auth Page UI

---

src/modules/Auth/index.tsx

Chaged payload of login from name and email to token for verification of the user form backend.

[Staging] Improvement_User_login

---

src/modules/details/components/EditTicketForm.tsx
src/modules/details/index.tsx

Hide the EditIcon from employee where he cant access it
Hide the fields from employee where he can't edit it

[Staging] Fix UI

---

src/modules/shared/UploadBucket.tsx

Removed upload button from create and edit page.

[Staging] remove update button

---

src/modules/details/index.tsx

[Staging] Fixed edit button

---

src/apis/utils/mediaUpload/awsmedia.ts
src/modules/shared/UploadBucket.tsx

Fixed issue of upload image on s3 bucket.

Fixed upload image issue in s3 bucket.

---

src/modules/details/components/EditTicketForm.tsx
src/modules/details/index.tsx

Fix edit button

---

src/modules/dashboard/index.tsx
src/modules/details/details.hook.ts
src/modules/shared/Button.tsx

Navigate the create button
Resolved the typescript error
Spell check

Temporaray_Fix

---

src/modules/shared/UploadBucket.tsx

Removed upload button from create and edit page.

Remove update button

---

src/modules/Auth/index.tsx

Chaged payload of login from name and email to token for verification of the user form backend.

Improvement_User_login

---

src/modules/shared/ComplaintCard.tsx

[Staging] Renamed the fields in ticket

---

src/apis/utils/mediaUpload/awsmedia.ts
src/modules/Ticket/index.tsx
src/modules/details/components/EditTicketForm.tsx

Upload file to s3 bucket using presigned url created from backend

[Staging] Fix/presigned url

---

src/apis/utils/mediaUpload/awsmedia.ts
src/modules/details/components/ImageTag.tsx

Added logic to fetch image from s3 bucket

[Staging] Fix/upload image

---

src/modules/shared/ComplaintCard.tsx

Renamed the field the in the ticket.

Renamed the fields in ticket

---

src/apis/utils/mediaUpload/awsmedia.ts

Make the post call to the api for uploading file

[Stagin] fix/upload_image_to_s3

---

src/modules/Category/category.service.ts
src/modules/Category/constanst.ts
src/modules/Category/index.tsx
src/modules/Category/type.ts

-Added the fields sla_unit and sla_duration type in create category form
-Renamed the DailogTitle

[Staging] Fix/create new category

---

src/modules/Ticket/index.tsx
src/modules/details/index.tsx

-Display multiline text correctly in description box
-Updated the validation schema

[Staging] Description_box

---

src/modules/dashboard/dashboard.scss
src/modules/shared/UploadBucket.tsx

Adjusted the margin for upload button.

[Staging] Fix/upload button

---

src/modules/dashboard/dashboard.scss
src/modules/shared/UploadBucket.tsx
src/modules/shared/constants.ts

Fix/Upload_media
- Allowed upload csv file type
-  Added fize size limit note
Include any relevant links related to this PR (e.g., documentation, related PRs, design documents).
- https://github.com/joshsoftware/providesk_admin_ui/pull/88
Please specify the issue number that this PR fixes (if applicable).
Fixes # (issue number)
Briefly describe the new feature or enhancement included in this PR.
If there are any visual changes, please include before and after screenshots:
Provide the ticket number related to this PR (if applicable).
- Ticket Number: # (ticket number)

[Staging]Fix/upload_media

---

src/modules/dashboard/dashboard.scss
src/modules/shared/UploadBucket.tsx
src/modules/shared/constants.ts

- Added a  note for upload file size limit.
- Allowed .csv to upload.
- Increased the file size limit.
Include any relevant links related to this PR (e.g., documentation, related PRs, design documents).
- https://github.com/joshsoftware/providesk_admin_ui/pull/74
- .csv was not uploading
- There is no file size note
- Can upload the csv file.
- Ticket Number: # (927)

[927]Fix_Upload_Media

---

src/modules/dashboard/dashboard.scss
src/modules/dashboard/index.tsx
src/modules/details/constants.ts
src/modules/details/index.tsx
src/modules/details/type.ts
src/modules/shared/UploadBucket.tsx
src/modules/shared/constants.ts

Provide a summary of the changes you have made. Explain the problem this PR addresses or the feature it introduces.
Include any relevant links related to this PR (e.g., documentation, related PRs, design documents).
- [Link 1](url)
- [Link 2](url)
Please specify the issue number that this PR fixes (if applicable).
Fixes # (issue number)
Briefly describe the new feature or enhancement included in this PR.
If there are any visual changes, please include before and after screenshots:
Provide the ticket number related to this PR (if applicable).
- Ticket Number: # (ticket number)

Update ticket closing workflow

---

package-lock.json
src/App.tsx
src/modules/dashboard/index.tsx
src/shared/paginationContextType.ts
yarn.lock

I have resolved the issue of pagination page count set.  The setting was dissapearing when  user was navigating to next page.

Pagination set rowPageNumber issue solve

---

src/modules/shared/constants.ts

Provide a summary of the changes you have made. Explain the problem this PR addresses or the feature it introduces.
Include any relevant links related to this PR (e.g., documentation, related PRs, design documents).
- [Link 1](url)
- [Link 2](url)
Please specify the issue number that this PR fixes (if applicable).
Fixes # (issue number)
Briefly describe the new feature or enhancement included in this PR.
If there are any visual changes, please include before and after screenshots:
Provide the ticket number related to this PR (if applicable).
- Ticket Number: # (ticket number)

fix issue of zip for windows
